python eda_imagenet_kmeans.py --downstream=aircraft --path=data/Filter/aircraft/openset_imagenet_subset_codelength_512_hash_k483_aircraft_kmeans.txt --path_label=data/imagenet_class_index.json
python eda_imagenet_kmeans.py --downstream=cars --path=data/Filter/cars/openset_imagenet_subset_codelength_512_hash_k100_cars_kmeans.txt --path_label=data/imagenet_class_index.json
python eda_imagenet_kmeans.py --downstream=celeba --path=data/Filter/celeba/openset_imagenet_subset_codelength_512_hash_k186_celeba_kmeans.txt --path_label=data/imagenet_class_index.json
python eda_imagenet_kmeans.py --downstream=cub --path=data/Filter/cub/openset_imagenet_subset_codelength_512_hash_k182_cub_kmeans.txt --path_label=data/imagenet_class_index.json
python eda_imagenet_kmeans.py --downstream=dogs --path=data/Filter/dogs/openset_imagenet_subset_codelength_512_hash_k2_dogs_kmeans.txt --path_label=data/imagenet_class_index.json
python eda_imagenet_kmeans.py --downstream=dtd --path=data/Filter/dtd/openset_imagenet_subset_codelength_512_hash_k35_dtd_kmeans.txt --path_label=data/imagenet_class_index.json
python eda_imagenet_kmeans.py --downstream=flowers --path=data/Filter/flowers/openset_imagenet_subset_codelength_512_hash_k657_flowers_kmeans.txt --path_label=data/imagenet_class_index.json
python eda_imagenet_kmeans.py --downstream=food11 --path=data/Filter/food11/openset_imagenet_subset_codelength_512_hash_k150_food11_kmeans.txt --path_label=data/imagenet_class_index.json
python eda_imagenet_kmeans.py --downstream=mit67 --path=data/Filter/mit67/openset_imagenet_subset_codelength_512_hash_k39_mit67_kmeans.txt --path_label=data/imagenet_class_index.json
python eda_imagenet_kmeans.py --downstream=pets --path=data/Filter/pets/openset_imagenet_subset_codelength_512_hash_k145_pets_kmeans.txt --path_label=data/imagenet_class_index.json
python eda_imagenet_kmeans.py --downstream=stanford40 --path=data/Filter/stanford40/openset_imagenet_subset_codelength_512_hash_k18_stanford40_kmeans.txt --path_label=data/imagenet_class_index.json
